<?php 
	$lang = array(
		                 'langue' => 'Fr',
		                 'addresseEmail' => 'vor kon maill',
		                 'motDePasse' => 'ich mot the pass', 
		                 'seConnecter' => 'Se connecter',
		                 'enregistrer' => 'S\'enregistrer',
		                  'creerUnNouveauPatient' => 'Creer un nouveau patient', 
		                  'leChampsAvec*SontObligatoires' => 'les champs avec * sont obligatoires', 
		                  'nom' => 'Nom', 
		                  'prenom' => 'Prénom', 
		                  'sexe' => 'Sexe', 
		                  'choisir' => 'Choisir', 
		                  'dateDdeNaissance' => 'DDN', 
		                  'region' => 'Région', 
		                  'choisirUneRegion' => 'Choisir une region', 
		                  'departement' => 'Département', 
		                  'choisirUnDepartement' => 'Choisir un département', 
		                  'arrondissement' => 'Arrondissement', 
		                  'choisirUnArrondissement' => 'Choisir un arrondissement', 
		                  'addresse' => 'Adresse', 
		                  'email' => 'Email', 
		                  'motDePasse' => 'Mot de passe',
		                  //pour l'accueil
		                  'confirmation' => 'Confirmation',
		                  'telephone1' => 'Téléphone1',
		                  'telephone2' => 'Téléphone2',
		                  'typeDeDiabete' => "Type de Diabète",

		                  'choisirUnType' => 'Choisir un type',
		                  'poids' => 'Poids ',
				          'taille' => 'Taille(cm)',								                   
				          'personneDurgence' => 'Personne d\'urgence',								              
				          'telephoneDurgence' => 'elphone d\'urgence',								                   
				          'annuler' => 'Annuler',								                   
				          'enregistrer' => 'Enregistrer',

		                  'monJournal' => 'Mon journal',
		                  'donnees' => 'Données',
		                  // pour la partie A PROPOS 
		                  'messages' => 'Messages',
		                  'preferences' => 'Preferences',
		                  'faq' => 'FAQ',
		                  'aPreoposDeNous' => "A propos de nous",
		                  'quitter' => 'Quitter',
		                  'journal' => "Journal",
		                  'editer' => 'Editer Mes Infos',
		                  'nouvelleMesure' => 'Nouvelle mésure',
		                  'tel' => 'Tel',
		                  'tel2' => 'Tel2',
		                  'urgence' => 'Urgence',
		                  'telUrgence' => 'Tel Urgence',
		                  'medecinTraitant' => 'Médecin traitant',
		                  //galerie space
		                  'rappelContoleApresRepas' => 'Rappels Controle après repas',
		                  'alarmePreventiveHypoglycémie' => 'Alarme préventive hypoglycémie',
		                  'creneauDateHeure' => 'Créneau/Date/heure',

		                  'creneau' => "Créneau",
		                  //pour la page d'inscription
		                  'rechercher' => "Rechercher",
		                  'glycemie' => "Glycémie",
		                  'insuline' => "Insuline",
		                  'acetone' => "Acétone",
		                  'dateEtHeure' => "Date et heure",
		                  'pa' => "P.A",
		                  'hba1c' => "Hba1c",
		                  'notes' => "Notes",

		                  'actions' => "Actions",
		                  'valeur' => "Valeur",
		                  'pressionArterielle' => "Pression artérielle",
		                  'donneesEnregistrees' => "Données enregistrées",
		                  'imprimerGenererPdf' => "imprimer/générer Pdf",
		                  'transfererParMail' => "Transférer par mail",
		                  'dateDeDebut' => "Date de début",
		                  'DateDeFin' => "Date de fin",
		                  'filtrer' => "Filtrer",
		                  'dates' => "Dates",
		                  'auLever' => "Au lever" ,
		                  //evenement en cour de realisation
		                  'avantLePetitDejeuner' => "Avant le petit dejeuner",
		                  //evenement realisés
		                  'apresLePetitDejeuner' => "Apres le petit dejeuner",   
		                  'apresLeDejeuner' => "Apres le djeuner",   
		                  'avantLeDejeuner' => "Avant le dejeuner",   
		                  'avantLeDiner' => "Avant le diner",   
		                  'apresLeDiner' => "Apres le diner",   
		                  'auCoucher' => "Au coucher",   
		                  'nouveuxMessages' => "Nouveaux messages",   
		                  'moiLe' => "Moi le",   
		                  'le' => "Le",   
		                  'mesPreferences' => "Mes préférences",   
		                  'alarme' => "Alarme",   
		                  'unites' => "unités",
		                   //evenement Futures
		                  'mesures' => "Mesures", 
		                  'profilUtilisateur' => "Profil Utilisateur",   

		                  'modifier' => "Modifier",
		                  //page partenaire actuels
		                  'modifierLeMotDePasse' => "Modifier le mot de passe",
		                  'infoVousAvezEteDeconnecte'=>"Info! Vous avez été déconnecté. ",

		                  'erreurAdresseEmailEtOuLeMotDePasseNeCorrespondentPas'=>' Erreur! L\'adresse email et/ou le mot de passe ne correspondent pas.',
		                  'mesPatients'=>'Mes Patients',
		                  'messages'=>'Messages',
		                  'listeDePatientsSuivis'=>'Liste de patients suivis',
		                  'suivreUnNouveauPatient'=>'Suivre un nouveau patient',
		                  'nomDuPatient'=>'Nom du patient',
		                  'interpretation'=>'Interpretation',
		                  'enAttenteApprobation'=>'En attente d\'approbation',
		                  'surpoids'=>'Surpoids',
		                  'Obésité morbide ou massive'=>'Obésité morbide ou massive',
		                  'Obésité modérée'=>'Obésité modérée',
		                  'nouveauxMessages'=>'nouveaux messages',
		                  'a'=>'à',
		                  'envoyer'=>'Envoyer',
		                  'ecrireUnNouveauMessage'=>'Ecrire un nouveau message',
		                  'accueil'=>'Accueil',
		                  'patients'=>'Patients',
		                  'medecins'=>'Médecins',
		                  'utilisateurs'=>'Utilisateurs',
		                  'patientsEnregistres'=>'Patients enregistrés',
		                  'medecinsEnregistres'=>'Medécins Enregistrés',
		                  'patientsSuivis'=>'patients Suivis',
		                  'medecinsSuivis'=>'Médecins Suivis',
		                  'patientsConnectes'=>'patients Connectés',
		                  'medecinsConnectes '=>'Médecins connectés',
		                  'patientsNonSuivis'=>'Patients non suivis',
		                  'utilisateursEnregistres'=>'Uutilisateurs enregistrés',
		                  'utilisateursConnectes'=>'Uutilisateurs Connectés ',
		                  'tableauDeBord'=>'Tableau de bord',

		                  'anneeEsperience'=>'ans d\'experiences',
		                  'approuver'=>'Approuver',
		                  'modifierMesInfos'=>'Modifier mes infos',
		                  'rappelsControlApresRepas'=>'Rappels controle après le repas',
		                  'alarmeHypo'=>'Alarme préventive hypoglycémie',
		                  'mesuresEnregistrer'=>'Mesures enregistées',


                          'Au lever'=>'At Rise',
                          'Avant le petit dejeuner'=>'Before breakfast',
                          'Avant le dejeuner'=>'Before the break fast',
                          'Apres le dejeuner'=>'After lunch',
                          'Avant le diner'=>'Before dinner',
                          'Apres le diner'=>'After dinner',
                          'Au coucher'=>'At bedtime',
                          'Apres le petit dejeune'=>'After breakfast',

                          'nom de la clinique' => 'Name of the hospital',
						  'infoCliniq'=>'Customization of the hospital',
						  'logo'=>'Logo of the hospital',
						  'phone'=>'Telephone of the hospital',
						  'siteWeb'=>'Website',
						  'autreInfoss'=>'Additional information',
						  'nouveauLogo'=>'New logo',
						  'changementLogo'=>'Logo change',
						  'infosDejamiseajour'=>'Information already updated',
						  'pasDeLogo'=>'No logo',



		             );
 ?>