<?php 
	$lang = array(
		                 'langue' => 'Deutch',
		                 'addresseEmail' => 'E-Mail-Adresse', 
		                 'motDePasse' => 'Passwort', 
		                 'seConnecter' => 'Einloggen', 
		                 'enregistrer1' => 'registrieren',
		                  'creerUnNouveauPatient' => 'Legen Sie einen neuen Patienten an', 
		                  'leChampsAvec*SontObligatoires' => 'Felder mit * sind Pflichtfelder', 
		                  'nom' => 'Name', 
		                  'prenom' => 'Vorname', 
		                  'sexe' => 'Geschlecht', 
		                  'choisir' => 'wählen', 
		                  'dateDdeNaissance' => 'Geburtsdatum', 
		                  'region' => 'Region', 
		                  'choisirUneRegion' => 'Wählen Sie eine Region aus', 
		                  'departement' => 'Abteilung', 
		                  'choisirUnDepartement' => 'Wählen Sie eine Abteilung aus', 
		                  'arrondissement' => 'Bezirk', 
		                  'choisirUnArrondissement' => 'Wählen Sie einen Bezirk aus', 
		                  'addresse' => 'Adresse', 
		                  'email' => 'E-Mail', 
		                  'selectionnerUnType'=>'Wählen Sie einen Typ aus',
		                  'DSA'=>'Geburtsdatum, Geschlecht und Adresse',
		                  'choisirSexe'=>'Bitte wähle dein Geschlecht',
		                  'localisation'=>'Standortinformationen',
		                  'contact'=>'Kontakte',
		                  'securite'=>'Sicherheit',
		                  'infoMedicale'=>'Medizinische Informationen',
		                  'selectionnerUnTypeDeDiabete'=>'Wählen Sie Ihre Art von Diabetes',
		                  'autreInfos'=>'Sonstige Angaben',
		                  'newMedecin'=>'neuer Arzt',
		                  'rechercherMedecin'=>'Finden Sie einen Arzt',
		                  'editerMed'=>'Arzt bearbeiten',


		                  //pour l'accueil
		                  'confirmation' => 'Bestätigung',
		                  'telephone1' => 'Telefon1',
		                  'telephone2' => 'Telefon2',
		                  'typeDeDiabete' => "Art des Diabetes",
		                  'choisirUneRegion'=>'Wählen Sie eine Region aus',

		                  'choisirUnType' => 'Wählen Sie einen Typ',
		                  'poids' => 'Gewicht',
				          'taille' => 'Größe(cm)',								                   
				          'personneDurgence' => 'Notfallperson',								              
				          'telephoneDurgence' => 'Notruf',								                   
				          'annuler' => 'stornieren',								                   
				          'enregistrer' => 'Rekord',
				          'photo'=>'Foto',
				          'nouvelleMesure'=>'Neue Messung',
				          'selectionner'=>'wählen',
				          'searchUsers'=>'Benutzersuche',

		                  'monJournal' => 'Mein Tagebuch',
		                  'donnees' => 'Daten',
		                  // pour la partie A PROPOS 
		                  'messages' => 'Beiträge',
		                  'preferences' => 'Voreinstellungen',
		                  'faq' => 'FAQ',
		                  'aPreoposDeNous' => "Über uns",
		                  'quitter' => 'verlassen',
		                  'journal' => "Mein Tagebuch",
		                  'editer' => 'Meine Informationen bearbeiten',
		                  'nouvelleMesure' => 'Neue Messung',
		                  'tel' => 'Telefon',
		                  'tel2' => 'Telefon2',
		                  'urgence' => 'Notfall',
		                  'telUrgence' => 'Notfalltelefon',
		                  'medecinTraitant' => 'Behandelnder Arzt',
		                  //galerie space
		                  'rappelContoleApresRepas' => 'Erinnern Sie sich nach dem Essen',
		                  'alarmePreventiveHypoglycémie' => 'Vorbeugender Alarm Hypoglykämie',
		                  'creneauDateHeure' => 'Nische / Datum / Zeit',
		                  'miseAjour'=>'Aktualisieren',
		                  'info'=>'Informationen',
		                  'donneesSuprimer'=>'Gelöschte Daten',
		                  'error'=>'Fehler',
		                  'desolerquelchose'=>'Tut uns Leid! Etwas ist schief gelaufen. Versuchen Sie es erneut',
		                  'malTourner'=>'Kann diesen Patienten nicht löschen',
		                  'malTournerMed'=>'Kann diesen Arzt nicht löschen',
		                  'impossibleKim'=>'Kann diese Benutzer nicht löschen',
		                  'nouveauMessages'=>'Neue Nachricht',
		                  'impossibleDeSuprimerCeMessage'=>'Diese Nachricht kann nicht gelöscht werden',
		                  'ecrireMessage'=>'eine Nachricht schreiben',
		                  'modal'=>'Neuen Patienten anlegen</span> (Felder mit <span class = "required"> * </ span> sind erforderlich)',
		                  'specialite'=>'Spezialität',
		                  'ancien'=>'Seniorität',



		                  'creneau' => "Nische",
		                  'inscription'=>'Anmeldung',
		                  'rechercher' => "Suche",
		                  'glycemie' => "Blutzucker",
		                  'insuline' => "Insulin",
		                  'acetone' => "Aceton",
		                  'dateEtHeure' => "Datum und Uhrzeit",
		                  'pa' => "P.A",
		                  'hba1c' => "Hba1c",
		                  'notes' => "Aufzeichnungen",
		                  'edietrPatient'=>'Patienten bearbeiten',
		                  'imc'=>'IMC',

		                  'actions' => "Aktion",
		                  'valeur' => "Wert",
		                  'pressionArterielle' => "Blutdruck",
		                  'donneesEnregistrees' => "Gespeicherte Daten",
		                  'imprimerGenererPdf' => "PDF drucken / erzeugen",
		                  'transfererParMail' => "Überweisung per E-Mail",
		                  'dateDeDebut' => "Startdatum",
		                  'dateDeFin' => "Enddatum",
		                  'filtrer' => "Filter",
		                  'dates' => "Termine",
		                  'auLever' => "Bei Sonnenaufgang" ,
		                  //evenement en cour de realisation
		                  'avantLePetitDejeuner' => "Vor dem Frühstück",
		                  //evenement realisés
		                  'apresLePetitDejeuner' => "Nach dem Frühstück",   
		                  'apresLeDejeuner' => "Nach dem Mittagessen",   
		                  'avantLeDejeuner' => "Vor dem Mittagessen",   
		                  'avantLeDiner' => "Vor dem Abendessen",   
		                  'apresLeDiner' => "Nach dem Abendessen",   
		                  'auCoucher' => "Vor dem Schlafengehen",   
		                  'nouveuxMessages' => "Neue Beiträge",   
		                  'moiLe' => "Ich",   
		                  'le' => "die",   
		                  'mesPreferences' => "Meine Vorlieben",   
		                  'alarme' => "Alarm",   
		                  'unites' => "Einheiten",
		                   //evenement Futures
		                  'mesures' => "Treppe", 
		                  'profilUtilisateur' => "Benutzerprofil",   

		                  'modifier' => "Veränderung",
		                  //page partenaire actuels
		                  'modifierLeMotDePasse' => "Passwort ändern",
		                  'infoVousAvezEteDeconnecte'=>"Sie wurden getrennt. ",

		                  'erreurAdresseEmailEtOuLeMotDePasseNeCorrespondentPas'=>'Fehler! Die E-Mail-Adresse und / oder das Passwort stimmen nicht überein.',
		                  'mesPatients'=>'Meine Patienten',
		                  'messages'=>'Beiträge',
		                  'listeDePatientsSuivis'=>'Liste der Patienten folgte',
		                  'suivreUnNouveauPatient'=>'Folgen Sie einem neuen Patienten',
		                  'nomDuPatient'=>'Name des Patienten',
		                  'interpretation'=>'Interpretationen',
		                  'enAttenteApprobation'=>'Warten auf Zustimmung',
		                  'Surpoids'=>'Übergewicht',
		                  'Obesite morbide ou massive'=>'Krankhafte oder massive Fettleibigkeit',
		                  'Obesite moderee'=>'Moderate Fettleibigkeit',
		                  'nouveauxMessages'=>'neue Nachrichten',
		                  'a'=>'zu',
		                  'envoyer'=>'Senden',
		                  'ecrireUnNouveauMessage'=>'Schreiben Sie eine neue Nachricht',
		                  'accueil'=>'willkommen',
		                  'patients'=>'Patienten',
		                  'medecins'=>'Ärzte',
		                  'utilisateurs'=>'Benutzer',
		                  'patientsEnregistres'=>'Registrierte Patienten',
		                  'medecinsEnregistres'=>'Registrierte Arzt',
		                  'medecins'=>'Arzt',
		                  'patientsSuivis'=>'Folgen Patienten',
		                  'medecinsSuivis'=>'Ärzte folgten',
		                  'patientsConnectes'=>'Verbundene Patienten',
		                  'medecinsConnectes'=>'Angeschlossene Ärzte',
		                  'patientsNonSuivis'=>'Patienten folgten nicht',
		                  'utilisateursEnregistres'=>'Registrierte Benutzer',
		                  'utilisateursConnectes'=>'Verbundene Benutzer ',
		                  'tableauDeBord'=>'Dashboard',
		                  'Obésité sévère'=>'
Schwere Fettleibigke',

		                  'anneeEsperience'=>'Jahre Erfahrung',
		                  'approuver'=>'Genehmigen',
		                  'modifierMesInfos'=>'Bearbeiten Sie meine Informationen',
		                  'rappelsControlApresRepas'=>'Erinnerungen kontrollieren nach dem Esse',
		                  'alarmeHypo'=>'orbeugender Alarm Hypoglykämie',
		                  'mesuresEnregistrer'=>'Aufgezeichnete Maßnahmen',
		                  'feminin'=>'Weiblich',
		                  'féminin'=>'Weiblich',
		                  'masculin'=>'Männlich',

		                  'Féminin'=>'Weiblich',
		                  'Masculin'=>'Männlich',

		                  'unites'=>'Einheiten',
		                  'editerMesure'=>'Messung bearbeiten',
		                  'addresseEmailVide'=>'Leere E-Mail-Adresse.',
		                  'motDePasseVide'=>'Leeres Passwort.',
		                  'nonCorrespondance'=>'Die E-Mail-Adresse und / oder das Passwort stimmen nicht überein.',
		                  'ProblemeDeConnexion'=>'Probleme beim Verbinden mit der Datenbank.',
		                  'voulezVousArretezDeSuivre'=>'Sie haben aufgehört, diesem Papier zu folgen.',
		                  'desolerPatient'=>'Tut uns Leid! Etwas ist schief gelaufen. Versuchen Sie es erneut.',
		                  'impossib'=>'Kann diesen Patienten nicht löschen.',
		                  'imprimer'=>'drucken',
		                  'nouveauPatient'=>'Neuer Patient',
		                  'rechercherUnPatient'=>'Einen Patienten finden',
		                  'nomPrenom'=>'Name / Vorname',
		                  'filtrerPar'=>'Filtern nach',
		                  'selectionner'=>'wählen',
		                  'debut'=>'Anfang',
		                  'fin'=>'Ende',
		                  'et'=>'und',
		                  'enteteMed'=>'Erstelle einen neuen Arzt</span> (Felder mit <span class = "required"> * </ span> sind erforderlich)',
		                  'login'=>'Login',
		                  'role'=>'Rolle',
		                  'dateAjout'=>'Datum hinzugefügt',
		                  'editerUse'=>'Benutzer bearbeiten',
		                  'ancienAdresse'=>'Alte Adresse',
		                  'nouvelleAdresse'=>'Neue Adresse',
		                  'changePassword'=>'Passwort ändern',
		                  'newPassword'=>'Neues Passwort',
		                  'rappelsControlApresRepas'=>'Kontrolle nach dem Essen abrufen',
		                  'message1'=>'Ihre Tracking-Anfrage wurde akzeptiert. Sie können den Patienten jetzt über Ihre Benutzeroberfläche verfolgen!',
		                  'typeDeDiabete'=>'Art des Diabetes',
		                   'sendMesssage'=>'Eine Nachricht senden',
		                   'journalPatient'=>'Patienten journal',
		                     'mesureSave'=>'Maßnahmen registriert',
		                     'sendMessage'=>'Gesandter eine Nachricht',
		                     'patient'=>'Geduldig',
		                     'message'=>'Nachricht',
		                     'messagesValidate'=>'Bitte geben Sie den Bestätigungscode ein, den Sie per E-Mail erhalten haben',
		                     'code'=>'Ein Bestätigungscode wurde Ihnen per E-Mail gesendet!',
		                     'validate'=>'bestätigen',
		                     'entete'=>'PATIENTENDATEI',
		                     'developperPar'=>'Entwickelt von',

                          'Au lever'=>'Beim Aufstehen',
                          'Avant le petit dejeuner'=>'Vor dem Fruehstueck',
                          'Avant le dejeuner'=>'Vor dem Mittagsessen',
                          'Apres le dejeuner'=>'Nach dem Mittagsessen',
                          'Avant le diner'=>'Vor dem Abendbro',
                          'Apres le diner'=>'Nach dem Abendbrot',
                          'Au coucher'=>'Vor dem Schlaf',
                          'Apres le petit dejeuner'=>'Nach dem Frühstück',
                          'Enregistrement effectue avec succes'=>'Die Aufnahme wird erfolgreich ausgeführt',
                          
                          'Heure de control hypoglycemie Modifiée avec succes'=>'Kontrollzeit für Hypoglykämie Erfolgreich geändert',
                          'Veuillez entez une date valide'=>'Bitte geben Sie ein gültiges Datum ein',
                          'modifierr'=>'Passwort erfolgreich geändert.',

                          'Dénutrition'=>'Unterernährung',
                          'Maigreur'=>'Magerkeit',
                          'Corpulence normale'=>'Normaler Körper',
                          'Surpoids'=>'Übergewicht',
                          'Obésité modéré'=>'oderate Fettleibigkeit',
                          'Obésité sévère'=>'Schwere Fettleibigkeit',
                          'Obésité morbide ou massive'=>'Krankhafte oder massive Fettleibigkeit',
                          'lang'=>'de',
                          'Type I'=>'Typ I',
                          'Type II'=>'Typ II',
                          'Femme enceinte'=>'Schwangere Frau',
                          'Type IV'=>'Typ IV',
                          'Administrateur'=>'Verwalter',
                          'medecin'=>'Arzt',
                          'Medecin'=>'Arzt',
                          'Patient'=>'Patient',

                          'Diabetologue'=>'Diabetologe',
                          'Generaliste'=>'Generalist',
                          'Nutritionniste'=>'Ernährungs',
                          'Autres'=>'Andere',

                          'Erreur 213 : Une erreur est survenue lors de l\'enregistrement de l\'unité patient, veuillez contacter l\'administrateur:'=>'Fehler 213: Beim Speichern der Patienteneinheit ist ein Fehler aufgetreten. Wenden Sie sich an den Administrator:',
                          'Patient enrégistré avec succès'=>'Patient erfolgreich registriert',
                          'Erreur 204: Une erreur est survenue lors de l\'enregistrement du patient, veuillez contacter l\'administrateur:'=>'Fehler 204: Beim Speichern des Patienten ist ein Fehler aufgetreten. Wenden Sie sich an den Administrator:', 


                            'Nom vide!'=>'Leerer Name!',
                          'Date de naissance vide !'=>'Geburtsdatum leer!',
                          'Sexe vide'=>'Leerer Sex',
                          'Adresse vide!'=>'Leere Adresse!',
                          'Région vide!'=>'Leere Region!',
                          'Département vide!'=>'Leere Abteilung!',
                          'Arrondissement vide!'=>'Rundung leer!',
                          'Email vide!'=>'Leere E-Mail!',
                          'Mot de passe vide!'=>'Passwort ist leer!',
                          'Confirmation vide!'=>'Bestätigung leer!',
                          'Poids vide!'=>'Leergewicht!',
                          'Taille vide!'=>'Leere Größe!',
                          'Téléphone vide!'=>'Leeres Telefon!',
                          'Personne d\'urgence vide!'=>'Leere Notfallperson!',
                          'Téléphone contact d\'urgence vide!'=>'Notruftelefon leeren!',
                          'Choisir un type de diabète!'=>'Wählen Sie eine Art von Diabetes!',
                          'Les mots de passe sont differents!'=>'Die Passwörter sind unterschiedlich!',
                          'Le mot de passe doit être de 6 caractères minimum!'=>'Das Passwort muss aus mindestens 6 Zeichen bestehen!',
                          'Email invalide'=>'Ungültige E-Mail',
                          'Format incorrect pour l\'adresse email!'=>'Falsches Format für die E-Mail-Adresse!',
                          'L\'adresse email n\'est pas valide!'=>'Die E-Mail-Adresse ist ungültig!',
                          'Valeur invalide pour le poids'=>'Ungültiger Wert für das Gewicht',
                          'Valeur négative pour le poids!'=>'Negativer Wert für das Gewicht!',
                           'Erreurs!'=>'Fehler!',
                           'couper'=>'Stoppen Sie die Verfolgung',
                           'message2'=>'Ihre Folgeanfrage wurde storniert, Sie können diesem Patienten nicht mehr folgen',
                           'raglages'=>'Einstellungen',
                           'activerRappelsControlApresRepas'=>'Aktivieren Sie die Erinnerungssteuerung nach dem Essen',
                          'activerAlarmeHypo'=>'Aktivieren Sie die vorbeugende Alarmhypoglykämie',
                            'Aucune donnée enrégistrée!!!'=>'Keine Daten registriert',



						  'nom de la clinique' => 'Name des Krankenhauses',
						  'infoCliniq'=>'Anpassung des Krankenhauses',
						  'logo'=>'Logo des Krankenhauses',
						  'phone'=>'Telefon des Krankenhauses',
						  'siteWeb'=>'Website',
						  'autreInfoss'=>'Zusätzliche Informationen',
						  'nouveauLogo'=>'Neues Logo',
						  'changementLogo'=>'Logoänderung',
						  'infosDejamiseajour'=>'Informationen bereits aktualisiert',
						  'pasDeLogo'=>'Kein Logo',


						  'M'=>'Männlich',
						  'F'=>'Weiblich',
						  'reglages'=>'Parameter',
						   'suprimer'=>'Auslöschen',


						   'Rechercher un patient à suivre'=>'Finden Sie einen Patienten, dem Sie folgen können',

						   'Liste des patients'=>'Liste der Patienten',
						   'liste_de_patients_suivis'=>'Liste der Patienten folgte',
                           'encours'=>'Diese Seite wird gerade geschrieben, aber wenn Sie ein Problem hatten oder eine Disfontionierung überqueren, zögern Sie nicht, an zu schreiben'






		                  



		             );
 ?>