<?php 
	$lang = array(
		                 'langue' => 'Fr',
		                 'addresseEmail' => 'Adresse Email',   
		                 'motDePasse' => 'Mot de passe',
		                 'seConnecter' => 'Se connecter',
		                 'enregistrer1' => 'S\'enregistrer',
		                  'creerUnNouveauPatient' => 'Creer un nouveau patient', 
		                  'leChampsAvec*SontObligatoires' => 'les champs avec * sont obligatoires', 
		                  'nom' => 'Nom', 
		                  'prenom' => 'Prénom', 
		                  'sexe' => 'Sexe', 
		                  'choisir' => 'Choisir', 
		                  'dateDdeNaissance' => 'Naissance', 
		                  'region' => 'Région', 
		                  'choisirUneRegion' => 'Choisir une region', 
		                  'departement' => 'Département', 
		                  'choisirUnDepartement' => 'Choisir un département', 
		                  'arrondissement' => 'Arrondissement', 
		                  'choisirUnArrondissement' => 'Choisir un arrondissement',  
		                  'addresse' => 'Adresse', 
		                  'email' => 'Email', 
		                  'motDePasse' => 'Mot de passe',
		                  'selectionnerUnType'=>'Sélectionner un type',
		                  'DSA'=>'Date de naissance, Sexe et Addresse',
		                  'choisirSexe'=>'Veuillez choisir votre sexe',
		                  'localisation'=>'Informations de localisations',
		                  'contact'=>'Contacts',
		                  'securite'=>'Sécurité',
		                  'infoMedicale'=>'Informations médicales',
		                  'selectionnerUnTypeDeDiabete'=>'Sélectionner votre type de diabète',
		                  'autreInfos'=>'Autre informations',
		                  'newMedecin'=>'Nouveau Medécin',
		                  'rechercherMedecin'=>'Rechercher un médécin',
		                  'editerMed'=>'Editer medécin',

		                  //pour l'accueil
		                  'confirmation' => 'Confirmation',
		                  'telephone1' => 'Téléphone1',
		                  'telephone2' => 'Téléphone2',
		                  'typeDeDiabete' => "Type de Diabète",
		                  'choisirUneRegion'=>'Choisir une région',
		                  'mesureSave'=>'Mesures enrégistrées',

		                  'choisirUnType' => 'Choisir un type',
		                  'poids' => 'Poids ',
				          'taille' => 'Taille(cm)',								                   
				          'personneDurgence' => 'Personne d\'urgence',								              
				          'telephoneDurgence' => 'Téléphone d\'urgence',								                   
				          'annuler' => 'Annuler',								                   
				          'enregistrer' => 'Enregistrer',
				          'photo'=>'Photo',
				          'nouvelleMesure'=>'Nouvelle mesure',
				          'selectionner'=>'Selectionner',
				          'searchUsers'=>'Recherche utilisateurs',
				          'sendMessage'=>'Envoyer un message',

		                  'monJournal' => 'Mon journal',
		                  'donnees' => 'Données',
		                  // pour la partie A PROPOS 
		                  'messages' => 'Messages',
		                  'preferences' => 'Preferences',
		                  'faq' => 'FAQ',
		                  'aPreoposDeNous' => "A propos de nous",
		                  'quitter' => 'Quitter',
		                  'journal' => "Journal",
		                  'editer' => 'Editer Mes Infos',
		                  'nouvelleMesure' => 'Nouvelle mésure',
		                  'tel' => 'Tel',
		                  'tel2' => 'Tel2',
		                  'urgence' => 'Urgence',
		                  'telUrgence' => 'Tel Urgence',
		                  'medecinTraitant' => 'Médecin traitant',
		                  //galerie space
		                  'rappelContoleApresRepas' => 'Rappels Controle après repas',
		                  'alarmePreventiveHypoglycémie' => 'Alarme préventive hypoglycémie',
		                  'creneauDateHeure' => 'Créneau/Date/heure',
		                  'miseAjour'=>'Mise a jour',
		                  'info'=>'Info',
		                  'donneesSuprimer'=>'Données supprimées',
		                  'error'=>'Error',
		                  'desolerquelchose'=>'Désolé! quelque chose a mal tourné, essayez à nouveau',
		                  'malTourner'=>'Impossible de supprimer ce patient',
		                  'malTournerMed'=>'Impossible de supprimer ce medécien',
		                  'impossibleKim'=>'Impossible de supprimer ce utilisateurs',
		                  'nouveauMessages'=>'Nouveau message',
		                  'impossibleDeSuprimerCeMessage'=>'Impossible de supprimer ce message',
		                  'ecrireMessage'=>'écrire un message',
		                  'modal'=>' Créer nouveau patient</span> (Les champs avec <span class="obligatoire">*</span> sont obligatoires)',
		                  'specialite'=>'Spécialité',
		                  'ancien'=>'Ancienneté',
		                  'suprimer'=>'Suprimer',

		                  ///added




		                  'creneau' => "Créneau",
		                  'inscription'=>'Inscription',
		                  'rechercher' => "Rechercher",
		                  'glycemie' => "Glycémie",
		                  'insuline' => "Insuline",
		                  'acetone' => "Acétone",
		                  'dateEtHeure' => "Date et heure",
		                  'pa' => "P.A",
		                  'hba1c' => "Hba1c",
		                  'notes' => "Notes",
		                  'edietrPatient'=>'Editer patient',
		                  'imc'=>'IMC',

		                  'actions' => "Actions",
		                  'valeur' => "Valeur",
		                  'pressionArterielle' => "Pression artérielle",
		                  'donneesEnregistrees' => "Données enregistrées",
		                  'imprimerGenererPdf' => "Imprimer/Générer Pdf",
		                  'transfererParMail' => "Transférer par mail",
		                  'dateDeDebut' => "Date de début",
		                  'dateDeFin' => "Date de fin",
		                  'filtrer' => "Filtrer",
		                  'dates' => "Dates",
		                  'auLever' => "Au lever" ,
		                  //evenement en cour de realisation
		                  'avantLePetitDejeuner' => "Avant le petit dejeuner",
		                  //evenement realisés
		                  'apresLePetitDejeuner' => "Apres le petit dejeuner",   
		                  'apresLeDejeuner' => "Apres le djeuner",   
		                  'avantLeDejeuner' => "Avant le dejeuner",   
		                  'avantLeDiner' => "Avant le diner",   
		                  'apresLeDiner' => "Apres le diner",   
		                  'auCoucher' => "Au coucher",   
		                  'nouveuxMessages' => "Nouveaux messages",   
		                  'moiLe' => "Moi le",   
		                  'le' => "Le",   
		                  'mesPreferences' => "Mes préférences",   
		                  'alarme' => "Alarme",   
		                  'unites' => "unités",
		                   //evenement Futures
		                  'mesures' => "Mesures", 
		                  'profilUtilisateur' => "Profil Utilisateur",   

		                  'modifier' => "Modifier",
		                  //page partenaire actuels
		                  'modifierLeMotDePasse' => "Modifier le mot de passe",
		                  'infoVousAvezEteDeconnecte'=>"Vous avez été déconnecté. ",

		                  'erreurAdresseEmailEtOuLeMotDePasseNeCorrespondentPas'=>' Erreur! L\'adresse email et/ou le mot de passe ne correspondent pas.',
		                  'mesPatients'=>'Mes Patients',
		                  'messages'=>'Messages',
		                  'listeDePatientsSuivis'=>'Liste des patients suivis',
		                  'suivreUnNouveauPatient'=>'Suivre un nouveau patient',
		                  'nomDuPatient'=>'Nom du patient',
		                  'interpretation'=>'Interpretation',
		                  'enAttenteApprobation'=>'En attente d\'approbation',
		                  'Surpoids'=>'Surpoids',
		                  'Obesite morbide ou massive'=>'Obésité morbide ou massive',
		                  'Obesite moderee'=>'Obésité modérée',
		                  'nouveauxMessages'=>'nouveaux messages',
		                  'Obesite severe'=>'Obésité sévère', 
		                  'a'=>'à',
		                  'envoyer'=>'Envoyer',
		                  'ecrireUnNouveauMessage'=>'Ecrire un nouveau message',
		                  'accueil'=>'Accueil',
		                  'patients'=>'Patients',
		                  'medecins'=>'Médecins',
		                  'utilisateurs'=>'Utilisateurs',
		                  'patientsEnregistres'=>'Patients enregistrés',
		                  'medecinsEnregistres'=>'Medécins Enregistrés',
		                  'medecins'=>'Medécins',
		                  'patientsSuivis'=>'patients Suivis',
		                  'medecinsSuivis'=>'Médecins Suivis',
		                  'patientsConnectes'=>'patients Connectés',
		                  'medecinsConnectes'=>'Médecins connectés',
		                  'patientsNonSuivis'=>'Patients non suivis',
		                  'utilisateursEnregistres'=>'Utilisateurs enregistrés',
		                  'utilisateursConnectes'=>'Utilisateurs Connectés ',
		                  'tableauDeBord'=>'Tableau de bord',

		                  'anneeEsperience'=>'ans d\'experiences',
		                  'approuver'=>'Approuver',
		                  'modifierMesInfos'=>'Modifier mes infos',
		                  'rappelsControlApresRepas'=>'Rappels controle après le repas',
		                  'alarmeHypo'=>'Alarme préventive hypoglycémie',
		                  'mesuresEnregistrer'=>'Mesures enregistées',
		                  'feminin'=>'Féminin',
		                  'féminin'=>'Féminin',
		                  'masculin'=>'Masculin',

		                  'feminin'=>'Féminin',
		                  'Féminin'=>'Féminin',
		                  'Masculin'=>'Masculin',


		                  'unites'=>'Unités',
		                  'editerMesure'=>'Editer mesure',
		                  'addresseEmailVide'=>'Adresse email vide.',
		                  'motDePasseVide'=>'Mot de passe vide.',
		                  'nonCorrespondance'=>'L\'adresse email et/ou le mot de passe ne correspondent pas.',
		                  'ProblemeDeConnexion'=>'Probleme de connexion à la base de données.',
		                  'voulezVousArretezDeSuivre'=>'Vous avez arrêté de suivre ce papier.',
		                  'desolerPatient'=>'Désolé! quelque chose a mal tourné, essayez à nouveau.',
		                  'impossib'=>'Impossible de supprimer ce patient.',
		                  'imprimer'=>'Imprimer',
		                  'nouveauPatient'=>'Nouveau patient',
		                  'rechercherUnPatient'=>'Rechercher un patient',
		                  'nomPrenom'=>'Nom/Prenom',
		                  'filtrerPar'=>'Filtrer par',
		                  'selectionner'=>'Sélectionner',
		                  'debut'=>'Début',
		                  'fin'=>'Fin',
		                  'et'=>'et',
		                  'enteteMed'=>'Créer nouveau medécin</span> (Les champs avec <span class="obligatoire">*</span> sont obligatoires)',
		                  'login'=>'Login',
		                  'role'=>'Rôle',
		                  'dateAjout'=>'Date ajout',
		                  'editerUse'=>'Editer l\'utilisateur',
		                  'ancienAdresse'=>'Ancienne Adresse',
		                  'nouvelleAdresse'=>'Nouvelle Adresse',
		                  'changePassword'=>'Changer le mot de passe',
		                  'newPassword'=>'Nouveau mot de passe',
		                  
		                  'journalPatient'=>'Journal du patient',
		                  'patient'=>'Patient',
		                  'message'=>'Message',
		                  'messagesValidate'=>'Veuillez saisir le code de validation reçu par mail',
		                  'code'=>'Un code de validation vous a été envoyé par mail!',
		                  'validate'=>'Valider',
		                  'entete'=>'DOSSIER DU PATIENT',
		                  'developperPar'=>'Devellopé par',
		                  //'rappelsControlApresRepas'=>'
                          //Erinnerungen kontrollieren nach dem Essen'

                          'Au lever'=>'Au lever',
                          'Avant le petit dejeuner'=>'Avant le petit dejeuner',
                          'Avant le dejeuner'=>'Avant le dejeuner',
                          'Apres le dejeuner'=>'Après le dejeuner',
                          'Avant le diner'=>'Avant le diner',
                          'Apres le diner'=>'Apres le diner',
                          'Au coucher'=>'Au coucher',
                          'Apres le petit dejeuner'=>'Apres le petit dejeuner',
                          'Enregistrement effectue avec succes'=>'Enregistrement effectué avec succès',
                          'Heure de control hypoglycemie Modifiée avec succes'=>'Heure de control hypoglycemie Modifiée avec succes',
                          'Veuillez entez une date valide'=>'Veuillez entez une date valide',
                          'Heure de rappel contole Modifiée avec succes'=>'Heure de rappel contole Modifiée avec succes',
                          'Heure de rappel contole Modifiée avec succes'=>'Rückrufzeitkontrolle erfolgreich geändert',
                          'modifierr'=>'Mot de passe changé avec succès.',
                          'Dénutrition'=>'Dénutrition',
                          'Maigreur'=>'Maigreur',
                          'Corpulence normale'=>'Corpulence normale',
                          'Surpoids'=>'Surpoids',
                          'Obésité modéré'=>'Obésité modéré',
                          'Obésité sévère'=>'Obésité sévère',
                          'Obésité morbide ou massive'=>'Obésité morbide ou massive',

                          'lang'=>'fr',
                          'Type I'=>'Type I',
                          'Type II'=>'Type II',
                          'Femme enceinte'=>'Femme enceinte',
                          'Type IV'=>'Type IV',

                          'Administrateur'=>'Administrateur',
                          'medecin'=>'Medecin',
                          'Medecin'=>'Medecin',
                          'Patient'=>'Patient',
                          'Diabetologue'=>'Diabetologue',
                          'Generaliste'=>'Generaliste',
                          'Nutritionniste'=>'Nutritionniste',
                          'Autres'=>'Autres',
                          'Erreur 213 : Une erreur est survenue lors de l\'enregistrement de l\'unité patient, veuillez contacter l\'administrateur:'=>'Erreur 213 : Une erreur est survenue lors de l\'enregistrement de l\'unité patient, veuillez contacter l\'administrateur:',
                          'Patient enrégistré avec succès'=>'Patient enrégistré avec succès',

                          'Erreur 204: Une erreur est survenue lors de l\'enregistrement du patient, veuillez contacter l\'administrateur:'
                          =>'Erreur 204: Une erreur est survenue lors de l\'enregistrement du patient, veuillez contacter l\'administrateur: ' ,

                          'Nom vide!'=>'Nom vide!',
                          'Date de naissance vide !'=>'Date de naissance vide !',
                          'Sexe vide'=>'Sexe vide',
                          'Adresse vide!'=>'Adresse vide!',
                          'Région vide!'=>'Région vide!',
                          'Département vide!'=>'Département vide!',
                          'Arrondissement vide!'=>'Arrondissement vide!',
                          'Email vide!'=>'Email vide!',
                          'Mot de passe vide!'=>'Mot de passe vide!',
                          'Confirmation vide!'=>'Confirmation vide!',
                          'Poids vide!'=>'Poids vide!',
                          'Taille vide!'=>'Taille vide!',
                          'Téléphone vide!'=>'Téléphone vide!',
                          'Personne d\'urgence vide!'=>'Personne d\'urgence vide!',
                          'Téléphone contact d\'urgence vide!'=>'Téléphone contact d\'urgence vide!',
                          'Choisir un type de diabète!'=>'Choisir un type de diabète!',
                          'Les mots de passe sont differents!'=>'Les mots de passe sont differents!',
                          'Le mot de passe doit être de 6 caractères minimum!'=>'Le mot de passe doit être de 6 caractères minimum!',
                          'Email invalide'=>'Email invalide',
                          'Format incorrect pour l\'adresse email!'=>'Format incorrect pour l\'adresse email!',
                          'L\'adresse email n\'est pas valide!'=>'L\'adresse email n\'est pas valide!',
                          'Valeur invalide pour le poids'=>'Valeur invalide pour le poids',
                          'Valeur négative pour le poids!'=>'Valeur négative pour le poids!',
                          'Erreurs!'=>'Erreurs!',
                          'couper'=>'Arreter son suivis',
                          'message1'=>'Votre demande de suivis a été accepté, vous pouvez désormais suivre ce patient',
                          'message2'=>'Votre demande de suivis a été annuler, vous  ne pouvez plus désormais suivre ce patient',
                          'reglages'=>'Paramètres',
                          'activerRappelsControlApresRepas'=>'Activer le rappels controle après le repas',
                          'activerAlarmeHypo'=>'Activer alarme préventive hypoglycémie',
						  'Aucune donnée enrégistrée!!!'=>'Aucune donnée enrégistrée!!!',

						  'nom de la clinique' => 'Nom de la l\'hopital',
						  'infoCliniq'=>'Personnalisation de la l\'hospital',
						  'logo'=>'Logo de l\'hopital',
						  'phone'=>'Telephone de l\'hospital',
						  'siteWeb'=>'Site internet',
						  'autreInfoss'=>'Information suplémentaire',
						  'nouveauLogo'=>'Nouveau logo',
						  'changementLogo'=>'Cahangement du logo',
						  'infosDejamiseajour'=>'Information déja mise a jours',
						  'pasDeLogo'=>'Pas de logo',

						  'M'=>'Masculin',
						  'F'=>'Feminin',

						  //added

						  'Rechercher un patient à suivre'=>'Rechercher un patient à suivre',
						  'Liste des patients'=>'Liste des patients',
						  'liste_de_patients_suivis'=>'Liste des patients suivis',
						  'encours'=>'Cette page est en cours d\'écriture mais si vous avez eu un problème ou croiser un disfontionement n\'hésitez pas à écrire au ' 
						  

                          





















		             );
 ?>